version: '3'
services:
  db:
    image: mysql:8.0.3
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: p4ssw0rd123
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  drupal:
    depends_on:
      - db
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    restart: always
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminman
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8081:80
    volumes:
     - /sessions
volumes:
  db_data: