version: '3'
services:
  db:
    image: mysql:8.0.3
    environment:
      MYSQL_DATABASE: drupal
      MYSQL_ROOT_PASSWORD: p4ssw0rd123
    volumes:
      - db_data:/var/lib/mysql
    restart: always
  drupal:
    depends_on:
      - db
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app:/app
    restart: always
volumes:
  db_data: